require('user.settings')
require('user.bindings')

-- Plugins Setup
require('user.plugins-setup')
require('user.plugins.bufferline')
require('user.plugins.lualine')
require('user.plugins.luasnip')
require('user.plugins.cmp')
require('user.plugins.lsp-inlay-hints')
require('user.plugins.lsp')
require('user.plugins.mason')
require('user.plugins.treesitter')
require('user.plugins.telescope')
require('user.plugins.gruvbox')
require('user.plugins.typescript')
require('user.plugins.svelte')
require('user.plugins.fugitive')
require('user.plugins.autopairs')
require('user.plugins.nullls')
require('user.plugins.prettier')
require('user.plugins.formatter')
require('user.plugins.vim-commentary')
require('user.plugins.todo-comments')
