require('user.settings')
require('user.bindings')

-- Plugins Setup
require('user.plugins-setup')
require('user.plugins.bufferline')
require('user.plugins.lualine')
require('user.plugins.luasnip')
require('user.plugins.lsp')
require('user.plugins.cmp')
require('user.plugins.treesitter')
require('user.plugins.telescope')
require('user.plugins.gruvbox')
require('user.plugins.svelte')
require('user.plugins.fugitive')
require('user.plugins.autopairs')
require('user.plugins.nullls')
