require('plugins.packer')
require('plugins.bufferline')
require('plugins.lualine')
require('plugins.luasnip')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.gruvbox')
require('plugins.svelte')
require('plugins.fugitive')
require('plugins.autopairs')
require('plugins.nullls')

